site_name: Learning With Fjj
site_description: 一个简洁的个人学习网站

theme: 
  name: readthedocs
  palette:
    primary: blue
    accent: light blue
  font:
    text: Roboto
    code: Roboto Mono

nav:
  - 主页: index.md
  - 关于我: about_me/me.md
  - 主要内容:
      - 秋招准备: course/index.md
      - 示例课程: course/example.md
  - 友链: friends/index.md
  - 关于: about/index.md

extra_css:
  - stylesheets/extra.css

