site_name: 我的网站名称
site_description: 一个简洁的个人学习网站

theme:
  name: material
  language: zh
  palette:
    scheme: default
    primary: white
    accent: indigo
  features:
    - navigation.tabs
    - navigation.top

nav:
  - 主页: index.md
  - 学习内容:
      - 学习内容首页: course/index.md
      - 示例课程: course/example.md
  - 友链: friends/index.md
  - 关于: about/index.md

extra_css:
  - stylesheets/extra.css

